# Generated by Django 3.2.7 on 2021-10-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id_servicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
