# Generated by Django 3.2.7 on 2021-10-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='id_categoria',
            new_name='categoria_id',
        ),
    ]
