# Generated by Django 3.2.7 on 2021-10-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_id_categoria_categoria_categoria_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id_post',
            new_name='post_id',
        ),
    ]
